stages:
  - setup
  - run
  - restart

setup_environment:
  stage: setup
  image: python:3.9
  script:
    - echo "Setting up the environment for multi-threading... Join @indiancheats"
    - pip install telebot flask aiogram python-telegram-bot pymongo || exit 1

run_script:
  stage: run
  image: python:3.9
  script:
    - echo "Granting execute permissions..."
    - chmod +x golem.py
    - echo "Running the multi-threaded script..."
    - python3 golem.py || exit 1

restart_pipeline:
  stage: restart
  image: python:3.9
  script:
    - echo "Waiting for 1 hour before restarting..."
    - sleep 3600
    - echo "Restarting the pipeline..."
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline || exit 1
  only:
    - main  # Adjust this for other branches
